purl:
  url: "https://sul-purl-stage.stanford.edu"

orcid_base_url: 'https://orcid.org'

datacite:
  prefix: '10.80343'

etd_apo: 'druid:bx911tp9024' # the APO that governs all ETDs

groups:
  dlss: 'sdr:etds-sul-staff'
  registrar: 'sdr:etds-registrar-staff'
  reports: 'sdr:etds-quarterly-reports'

preview_dir: <%= Rails.root.join('tmp', 'preview').to_s %>

sdr:
  local_workspace_root: /dor/workspace

peoplesoft:
  enabled: true
  client_id: ~
  client_secret: ~
  base_url: ~
  token_url: ~

ps_servers:
  - 'server1.example.com'
ps_ips:
  - '10.0.0.1'

# marc_workspace: individual stub records
marc_workspace: '~'

catalog:
  folio:
    okapi:
      url: "https://okapi-stage.example.com"
      username: "app_sdr"
      password: "supersecret"
      legacy_auth: true
    tenant_id: "example_tenant"
    marc_job_profile_uuid: ae0a94d0-1f8e-4177-bcf9-c3a90e4c9429
    marc_job_name: 'ETDs New'
    status:
      cataloged_uuid: 9634a5ab-9228-4703-baf2-4d12ebc77d56
    import:
      timeout_seconds: 300 # default value set in folio_client gem
      wait_seconds: 5 # wait longer between import checks to give the job enough time to be created and to finish
      max_checks: 10 # default value set in folio_client gem
    url: "https://folio-stage.stanford.edu" # base URL of folio instance (e.g. for linkout to record details page)

dor_services:
  url: 'http://localhost:3003'
  # To generate the token: docker compose run dor-services-app bin/rake generate_token
  token: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJDb250YWluZXJsYW5kIn0.Pnf8C9CNYGFCcERfdPSUMkQ7FqyS37Jbselcg3yeLeY

# ActiveAdmin configs
searchworks_uri: https://searchworks.stanford.edu/view/%<catalog_record_id>s
argo_url: https://argo.stanford.edu
stacks_uri: 'https://stacks.stanford.edu/file/%<druid>s/%<aug_diss_file_name>s'

etd_mail_from: 'etd-alerts@lists.stanford.edu'
etd_cataloging_list: 'etd-catload-reports@lists.stanford.edu'

mailable_environments:
  - 'prod'
  - 'test'

# Skip ETDs in the SDR Graveyard (withdrawn by registrar) or lost to us (possibly in great ETD migration of 2012)
skip_cataloging_alert: ['druid:gh926rx4162', 'druid:wz924gg6479']

# checkin keys for honeybadger (actual keys are in shared_configs per environment as needed)
# see https://app.honeybadger.io/projects/55164/check_ins
honeybadger_checkins:
  catalog_status: test
  ready_for_cataloging: test

dlss_admin: 'dummy3'
dlss_admin_pw: 'dummy4'

copyright_instructions_url: 'https://drive.google.com/file/d/1do8J5rZvpDUrGrkOAYOZ96qNIvy0abfd/view'

file_uploads_root: '/opt/app/etd/workspace'

supplemental_files:
  max_files: 20

permission_files:
  max_files: 20
