peoplesoft:
  base_url: 'https://registrar.example.edu/peoplesoft'
  token_url: 'http://tokensrus.example.edu'
  client_id: 'foo'
  client_secret: 'bar'

file_uploads_root: <%= Rails.root.join("tmp/storage") %>

supplemental_files:
  max_files: 2

permission_files:
  max_files: 2
